"""add restaurant logo_url

Revision ID: e4e545548c78
Revises: 29ea711193da
Create Date: 2026-08-16 13:17:53.678018
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e4e545548c78'
down_revision: Union[str, None] = '29ea711193da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('logo_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'logo_url')
    # ### end Alembic commands ###
